steps:
  # Construir la imagen de Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/elasticidad-api:$COMMIT_SHA', '.']
  
  # Subir la imagen al Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/elasticidad-api:$COMMIT_SHA']
  
  # Desplegar en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'elasticidad-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/elasticidad-api:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '900'
      - '--set-env-vars'
      - 'DEBUG=false,LOG_LEVEL=INFO'

images:
  - 'gcr.io/$PROJECT_ID/elasticidad-api:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY